defaults:
  - meta_base

name: bioMON_NB

cls:
  _target_: methods.bio_metaoptnet.BioMetaOptNet
  n_way: ${n_way}
  n_support: ${n_shot}
  head_model_params:
    model: NaiveBayes
    args:
      n_way: ${n_way}
      seed: 42
