defaults:
  - meta_base

name: bioMON_SVM

cls:
  _target_: methods.bio_metaoptnet.BioMetaOptNet
  n_way: ${n_way}
  n_support: ${n_shot}
  head_model_params:
    model: SVM
    args:
      n_way: ${n_way}
      seed: 42
      kernel: poly
      C: 1
      probability: true
