defaults:
  - dataset: tabula_muris
  - method: maml

model: FCNET
n_way: ???
n_shot: ???
n_query: ???

mode: train

exp:
  name: ???
  save_freq: 10
  resume: false
  seed: 42
  val_freq: 1

optimizer: Adam
lr: 0.001
optimizer_cls:
  _target_: torch.optim.${optimizer}
  lr: ${lr}

checkpoint:
  dir: checkpoints/${exp.name}/${dataset.name}/${method.name}_${model}
  test_iter: best_model
  time: latest

results:
  dir: results/${exp.name}/${dataset.name}/${method.name}_${model}/${n_way}w${n_shot}s${n_query}q

wandb:
  project: BioMed-DL
  entity: manosxatzakiss2000
  mode: "offline" # Can set to offline, disabled

iter_num: 1
